Universe           = vanilla
Initialdir         = /sphenix/user/ChengWei/coldQCD_code/ForwardCaloNtuplizer/macro
Executable         = run_job.sh
PeriodicHold       = (NumJobStarts>=1 && JobStatus == 1)
concurrency_limits = CONCURRENCY_LIMIT_DEFAULT:100
request_memory     = 4GB
Priority           = 20
job_lease_duration = 86400

runnumber          = 51195
Nevent             = -1
input_filename     = /sphenix/tg/tg01/commissioning/pinkenbu/vernier/DST_TRIGGERED_EVENT_run2pp_new_2024p003-00051195-$INT(process,%05d).root
output_directory   = /sphenix/tg/tg01/coldqcd/cwshih/test/run_51195/from_Chris_mbdZ/ntuple_file_waveform_GL1P
outputFile         = ntuple_run$(runnumber)_$INT(process,%05d).root

Output             = $(output_directory)/cw_log/condor_$(process).out
Error              = $(output_directory)/cw_log/condor_$(process).err
Log                = $(output_directory)/cw_log/condor_$(process).log
Arguments          = "$(process) $(Nevent) $(input_filename) $(output_directory) $(outputFile)"
Queue 16